# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Create release

on:
    pull_request:
        types:
            - closed
        branches:
            - production

jobs:
    release:

        runs-on: ubuntu-18.04
        timeout-minutes: 10
        if: github.event.pull_request.merged == true

        steps:
            -   name: Create Release
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    commitish: ${{ github.event.pull_request.head.ref }}
                    tag_name: "0.0.1"
                    release_name: Test
                    body: Test
                    draft: false
                    prerelease: false
