# This is a basic workflow to help you get started with Actions

name: CI

on: 
  workflow_dispatch:
    inputs:
      pull:
        description: 'Pull request id'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            repository: randilfernando/github-actions-test
            ref: ${{ github.head_ref }}
            token: ${{ secrets.GITHUB_TOKEN }}
            path: ./pull_request
